#!/bin/bash
# Copyright (C) 2000-2016 Synology Inc. All rights reserved.

case ${MakeClean} in
	[Yy][Ee][Ss])
		make clean
		;;
esac

# You can use CC CFLAGS LD LDFLAGS CXX CXXFLAGS AR RANLIB READELF STRIP here
#echo "${CC} ${CFLAGS} monitor/crc.c -o crc"
#${CC} ${CFLAGS} monitor/crc.c -o crc
#all:	monitor/hex-monitor.c monitor/swb-serial.c monitor/smi-serial.c monitor/smi-monitor.c monitor/crc.c comandline/smi.c
	$(CC) $(OPT) -o smi commandline/smi.c
	$(CC) $(OPT) -o hex-monitor monitor/hex-monitor.c
	$(CC) $(OPT) -o smi-monitor monitor/swb-serial.c monitor/smi-serial.c monitor/smi-monitor.c
	$(CC) $(OPT) -o crc monitor/crc.c
	$(CC) $(OPT) -o prog monitor/prog.c



# Or you can use Makefile to genarate executable.
#echo .
#echo "###########################################################################"
#echo "###########################################################################"
#echo "make ${MAKE_FLAGS}"
#make ${MAKE_FLAGS}
#echo "###########################################################################"
#echo "###########################################################################"
#echo .
