CC = gcc
OPT = -g -Wall

# default target
default: all

# compile only smi commandline
all:  smi.c
	$(CC) $(OPT) -o smi smi.c

# removes all object, temporary an executable files
clean:
	$(RM) count *.o *~
  
