#!/bin/sh

### This script will be executed when package installed and upgraded.
### Actions after package installed.
### ex. create database, create symbolic link...

ln -sf $SYNOPKG_PKGDEST/usr/bin/smi-monitor /usr/bin/
ln -sf $SYNOPKG_PKGDEST/usr/bin/crc /usr/bin/
ln -sf $SYNOPKG_PKGDEST/usr/bin/prog /usr/bin/

exit 0
