#!/bin/sh

### This script will be executed when package uninstalled and upgraded.
### Actions after package uninstalled.
### ex. remove garbage files.

rm -f /usr/bin/smi-monitor
rm -f /usr/bin/crc

exit 0
