#!/bin/sh

case $1 in
	start)
		insmod /lib/modules/usbserial.ko
		insmod /lib/modules/ftdi_sio.ko
		echo "FTDI-USB Treiber wurden geladen." > $SYNOPKG_TEMP_LOGFILE 
		exit 0
		;;
	stop)
		rmmod fdti_sio
		rmmod usbserial
		echo "FTDI-SUB Treiber wurden entladen." > $SYNOPKG_TEMP_LOGFILE
		;;
	status)
		echo "status" > $SYNOPKG_TEMP_LOGFILE
		exit 0
		;;
	log)
		echo "log" > $SYNOPKG_TEMP_LOGFILE
		exit 0
		;;
	*)
		exit 1
		;;
esac
