#!/bin/sh

case $1 in
	start)
		insmod /lib/modules/usbserial.ko
		insmod /lib/modules/ftdi_sio.ko
		echo "FTDI-USB Treiber wurden geladen." > $SYNOPKG_TEMP_LOGFILE 
		exit 0
		;;
	stop)
		exit 0
		;;
	status)
		exit 0
		;;
	log)
		exit 0
		;;
	*)
		exit 1
		;;
esac
